type TTerminalThemeVariant = 'light' | 'dark';

interface ITerminalThemeColors {
  background: string;
  foreground: string;
  cursor: string;
  cursorAccent: string;
  selectionBackground: string;
  selectionForeground: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

interface ITerminalTheme {
  id: string;
  name: string;
  variant: TTerminalThemeVariant;
  colors: ITerminalThemeColors;
}

interface ITerminalThemeIds {
  light: string;
  dark: string;
}

const TERMINAL_THEMES: ITerminalTheme[] = [
  // --- Dark ---
  {
    id: 'snazzy',
    name: 'Snazzy',
    variant: 'dark',
    colors: {
      background: '#1e1f29',
      foreground: '#ebece6',
      cursor: '#e4e4e4',
      cursorAccent: '#1e1f29',
      selectionBackground: '#81aec6',
      selectionForeground: '#000000',
      black: '#000000',
      red: '#fc4346',
      green: '#50fb7c',
      yellow: '#f0fb8c',
      blue: '#49baff',
      magenta: '#fc4cb4',
      cyan: '#8be9fe',
      white: '#ededec',
      brightBlack: '#555555',
      brightRed: '#fc4346',
      brightGreen: '#50fb7c',
      brightYellow: '#f0fb8c',
      brightBlue: '#49baff',
      brightMagenta: '#fc4cb4',
      brightCyan: '#8be9fe',
      brightWhite: '#ededec',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    variant: 'dark',
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      cursor: '#f8f8f2',
      cursorAccent: '#282a36',
      selectionBackground: '#44475a',
      selectionForeground: '#f8f8f2',
      black: '#21222c',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      magenta: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      brightBlack: '#6272a4',
      brightRed: '#ff6e6e',
      brightGreen: '#69ff94',
      brightYellow: '#ffffa5',
      brightBlue: '#d6acff',
      brightMagenta: '#ff92df',
      brightCyan: '#a4ffff',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    variant: 'dark',
    colors: {
      background: '#282c34',
      foreground: '#abb2bf',
      cursor: '#528bff',
      cursorAccent: '#282c34',
      selectionBackground: '#3e4451',
      selectionForeground: '#abb2bf',
      black: '#282c34',
      red: '#e06c75',
      green: '#98c379',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#56b6c2',
      white: '#abb2bf',
      brightBlack: '#5c6370',
      brightRed: '#e06c75',
      brightGreen: '#98c379',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#56b6c2',
      brightWhite: '#ffffff',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    variant: 'dark',
    colors: {
      background: '#1a1b26',
      foreground: '#a9b1d6',
      cursor: '#c0caf5',
      cursorAccent: '#1a1b26',
      selectionBackground: '#33467c',
      selectionForeground: '#a9b1d6',
      black: '#15161e',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      magenta: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      brightBlack: '#414868',
      brightRed: '#f7768e',
      brightGreen: '#9ece6a',
      brightYellow: '#e0af68',
      brightBlue: '#7aa2f7',
      brightMagenta: '#bb9af7',
      brightCyan: '#7dcfff',
      brightWhite: '#c0caf5',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    variant: 'dark',
    colors: {
      background: '#2e3440',
      foreground: '#d8dee9',
      cursor: '#d8dee9',
      cursorAccent: '#2e3440',
      selectionBackground: '#434c5e',
      selectionForeground: '#d8dee9',
      black: '#3b4252',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#e5e9f0',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    variant: 'dark',
    colors: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      cursorAccent: '#1e1e2e',
      selectionBackground: '#585b70',
      selectionForeground: '#cdd6f4',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
  },
  // --- Light ---
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    variant: 'light',
    colors: {
      background: '#eff1f5',
      foreground: '#4c4f69',
      cursor: '#dc8a78',
      cursorAccent: '#eff1f5',
      selectionBackground: '#acb0be',
      selectionForeground: '#4c4f69',
      black: '#5c5f77',
      red: '#d20f39',
      green: '#40a02b',
      yellow: '#df8e1d',
      blue: '#1e66f5',
      magenta: '#ea76cb',
      cyan: '#179299',
      white: '#acb0be',
      brightBlack: '#6c6f85',
      brightRed: '#d20f39',
      brightGreen: '#40a02b',
      brightYellow: '#df8e1d',
      brightBlue: '#1e66f5',
      brightMagenta: '#ea76cb',
      brightCyan: '#179299',
      brightWhite: '#bcc0cc',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    variant: 'light',
    colors: {
      background: '#f6f8fa',
      foreground: '#24292f',
      cursor: '#044289',
      cursorAccent: '#f6f8fa',
      selectionBackground: '#b6d7ff',
      selectionForeground: '#24292f',
      black: '#24292f',
      red: '#cf222e',
      green: '#116329',
      yellow: '#9a6700',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
      white: '#6e7781',
      brightBlack: '#57606a',
      brightRed: '#a40e26',
      brightGreen: '#1a7f37',
      brightYellow: '#bf8700',
      brightBlue: '#218bff',
      brightMagenta: '#a475f9',
      brightCyan: '#3192aa',
      brightWhite: '#8c959f',
    },
  },
  {
    id: 'one-light',
    name: 'One Light',
    variant: 'light',
    colors: {
      background: '#fafafa',
      foreground: '#383a42',
      cursor: '#526eff',
      cursorAccent: '#fafafa',
      selectionBackground: '#e5e5e6',
      selectionForeground: '#383a42',
      black: '#383a42',
      red: '#e45649',
      green: '#50a14f',
      yellow: '#c18401',
      blue: '#4078f2',
      magenta: '#a626a4',
      cyan: '#0184bc',
      white: '#a0a1a7',
      brightBlack: '#696c77',
      brightRed: '#e45649',
      brightGreen: '#50a14f',
      brightYellow: '#c18401',
      brightBlue: '#4078f2',
      brightMagenta: '#a626a4',
      brightCyan: '#0184bc',
      brightWhite: '#d4d4d4',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    variant: 'light',
    colors: {
      background: '#fdf6e3',
      foreground: '#657b83',
      cursor: '#657b83',
      cursorAccent: '#fdf6e3',
      selectionBackground: '#eee8d5',
      selectionForeground: '#657b83',
      black: '#073642',
      red: '#dc322f',
      green: '#859900',
      yellow: '#b58900',
      blue: '#268bd2',
      magenta: '#d33682',
      cyan: '#2aa198',
      white: '#eee8d5',
      brightBlack: '#002b36',
      brightRed: '#cb4b16',
      brightGreen: '#586e75',
      brightYellow: '#657b83',
      brightBlue: '#839496',
      brightMagenta: '#6c71c4',
      brightCyan: '#93a1a1',
      brightWhite: '#fdf6e3',
    },
  },
  {
    id: 'tokyo-night-light',
    name: 'Tokyo Night Light',
    variant: 'light',
    colors: {
      background: '#e1e2e7',
      foreground: '#3760bf',
      cursor: '#3760bf',
      cursorAccent: '#e1e2e7',
      selectionBackground: '#b6bfe2',
      selectionForeground: '#3760bf',
      black: '#e9e9ed',
      red: '#f52a65',
      green: '#587539',
      yellow: '#8c6c3e',
      blue: '#2e7de9',
      magenta: '#9854f1',
      cyan: '#007197',
      white: '#6172b0',
      brightBlack: '#a1a6c5',
      brightRed: '#f52a65',
      brightGreen: '#587539',
      brightYellow: '#8c6c3e',
      brightBlue: '#2e7de9',
      brightMagenta: '#9854f1',
      brightCyan: '#007197',
      brightWhite: '#3760bf',
    },
  },
  {
    id: 'nord-light',
    name: 'Nord Light',
    variant: 'light',
    colors: {
      background: '#eceff4',
      foreground: '#2e3440',
      cursor: '#2e3440',
      cursorAccent: '#eceff4',
      selectionBackground: '#d8dee9',
      selectionForeground: '#2e3440',
      black: '#2e3440',
      red: '#bf616a',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      blue: '#81a1c1',
      magenta: '#b48ead',
      cyan: '#88c0d0',
      white: '#d8dee9',
      brightBlack: '#4c566a',
      brightRed: '#bf616a',
      brightGreen: '#a3be8c',
      brightYellow: '#ebcb8b',
      brightBlue: '#81a1c1',
      brightMagenta: '#b48ead',
      brightCyan: '#8fbcbb',
      brightWhite: '#eceff4',
    },
  },
];

const DEFAULT_THEME_IDS: ITerminalThemeIds = {
  light: 'catppuccin-latte',
  dark: 'snazzy',
};

const getTerminalTheme = (id: string): ITerminalTheme =>
  TERMINAL_THEMES.find((t) => t.id === id) ?? TERMINAL_THEMES[0];

export { TERMINAL_THEMES, DEFAULT_THEME_IDS, getTerminalTheme };
export type { ITerminalTheme, ITerminalThemeColors, ITerminalThemeIds, TTerminalThemeVariant };
