import { memo } from 'react';
import type { IconType } from 'react-icons';
import { VscVscode } from 'react-icons/vsc';
import { FaAws } from 'react-icons/fa6';
import { BsTerminalFill } from 'react-icons/bs';
import {
  SiVim,
  SiNeovim,
  SiGnuemacs,
  SiHelix,
  SiGit,
  SiGithub,
  SiNodedotjs,
  SiDeno,
  SiBun,
  SiPython,
  SiGo,
  SiRuby,
  SiRust,
  SiSwift,
  SiDart,
  SiElixir,
  SiPerl,
  SiPhp,
  SiR,
  SiJulia,
  SiScala,
  SiZig,
  SiNpm,
  SiPnpm,
  SiYarn,
  SiPypi,
  SiHomebrew,
  SiArchlinux,
  SiFedora,
  SiUbuntu,
  SiCmake,
  SiGradle,
  SiApachemaven,
  SiWebpack,
  SiTypescript,
  SiDocker,
  SiKubernetes,
  SiHelm,
  SiGooglecloud,
  SiTerraform,
  SiAnsible,
  SiVagrant,
  SiCurl,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiTmux,
  SiGnuprivacyguard,
  SiOpenssl,
  SiJest,
  SiOpenjdk,
} from 'react-icons/si';
import {
  Hammer,
  Network,
  Activity,
  FolderTree,
  FileText,
  Shield,
  FileArchive,
} from 'lucide-react';
import OpenAIIcon from '@/components/icons/openai-icon';

type TProcessIconComponent = IconType | React.ComponentType<{ className?: string }>;

const SHELL_ICON: TProcessIconComponent = BsTerminalFill;

const PROCESS_ICON_MAP: Record<string, TProcessIconComponent> = {
  bash: SHELL_ICON,
  sh: SHELL_ICON,
  dash: SHELL_ICON,
  tcsh: SHELL_ICON,
  nu: SHELL_ICON,
  zsh: SHELL_ICON,
  fish: SHELL_ICON,
  vim: SiVim,
  vi: SiVim,
  nvim: SiNeovim,
  nano: SiGnuemacs,
  emacs: SiGnuemacs,
  hx: SiHelix,
  code: VscVscode,
  git: SiGit,
  gitui: SiGit,
  tig: SiGit,
  gh: SiGithub,
  lazygit: SiGit,
  jj: SiGit,
  lazyjj: SiGit,
  node: SiNodedotjs,
  deno: SiDeno,
  bun: SiBun,
  python: SiPython,
  python3: SiPython,
  go: SiGo,
  ruby: SiRuby,
  java: SiOpenjdk,
  rust: SiRust,
  rustc: SiRust,
  cargo: SiRust,
  swift: SiSwift,
  dart: SiDart,
  elixir: SiElixir,
  perl: SiPerl,
  php: SiPhp,
  R: SiR,
  julia: SiJulia,
  scala: SiScala,
  zig: SiZig,
  npm: SiNpm,
  pnpm: SiPnpm,
  yarn: SiYarn,
  pip: SiPypi,
  pip3: SiPypi,
  brew: SiHomebrew,
  apt: SiUbuntu,
  dnf: SiFedora,
  pacman: SiArchlinux,
  yay: SiArchlinux,
  paru: SiArchlinux,
  make: Hammer,
  cmake: SiCmake,
  gradle: SiGradle,
  maven: SiApachemaven,
  webpack: SiWebpack,
  tsc: SiTypescript,
  docker: SiDocker,
  lazydocker: SiDocker,
  kubectl: SiKubernetes,
  k9s: SiKubernetes,
  helm: SiHelm,
  minikube: SiKubernetes,
  aws: FaAws,
  gcloud: SiGooglecloud,
  terraform: SiTerraform,
  ansible: SiAnsible,
  vagrant: SiVagrant,
  ssh: Network,
  scp: Network,
  curl: SiCurl,
  wget: SiCurl,
  rsync: Network,
  ping: Network,
  htop: Activity,
  btop: Activity,
  top: Activity,
  btm: Activity,
  glances: Activity,
  mactop: Activity,
  ranger: FolderTree,
  yazi: FolderTree,
  lf: FolderTree,
  lfcd: FolderTree,
  mysql: SiMysql,
  psql: SiPostgresql,
  mongo: SiMongodb,
  redis: SiRedis,
  sqlite: SiSqlite,
  tmux: SiTmux,
  screen: SiTmux,
  sudo: Shield,
  bat: FileText,
  gpg: SiGnuprivacyguard,
  openssl: SiOpenssl,
  zip: FileArchive,
  unzip: FileArchive,
  jest: SiJest,
  codex: OpenAIIcon,
};

interface IProcessIconProps {
  process?: string | null;
  className?: string;
}

const ProcessIcon = ({ process, className }: IProcessIconProps) => {
  const Icon = (process && PROCESS_ICON_MAP[process]) || BsTerminalFill;
  return <Icon className={className} aria-hidden="true" />;
};

export default memo(ProcessIcon);
