const shared = {
  installCommand: 'npx --yes codexmux@latest',
};

module.exports = {
  en: {
    ...shared,
    langLabel: 'EN',
    nav: {
      capabilities: 'Capabilities',
      workflow: 'Workflow',
      boundary: 'Status',
      architecture: 'Architecture',
      install: 'Install',
      docs: 'Docs',
      start: 'Get started',
    },
    hero: {
      eyebrow: 'Codex session operations · one Linux engine',
      title: ['Run the work.', 'Find the context.', 'Govern the project.'],
      description: 'codexmux connects live Codex control, durable session review, and guarded project operations in one browser-based workspace.',
      guide: 'Open the quickstart',
      proof: ['Browser-first', 'Local-first data', 'Korean + English UI'],
      integration: 'Session analysis and project governance are built into codexmux—not linked as separate services.',
    },
    preview: {
      engine: 'Linux engine',
      ready: 'Workers ready',
      sessions: 'Session Explorer',
      search: 'Search messages, projects, models, tags…',
      results: [
        { project: 'codexmux', title: 'Governed scaffold rollout', meta: 'gpt-5.6 · 24 entries', state: 'Pinned' },
        { project: 'runtime-v2', title: 'Worker recovery verification', meta: 'gpt-5.6 · 17 entries', state: 'Replay' },
      ],
      governance: 'Project Governance',
      project: 'Managed Project · codexmux',
      documents: [
        { name: 'AGENTS.md', state: 'Guidance' },
        { name: 'CONTEXT.md', state: 'Indexed' },
        { name: 'Project Lifecycle', state: 'Operate' },
      ],
      action: 'Preview required before write',
      writeState: 'Guarded',
    },
    pillarsEyebrow: 'One operating surface',
    pillarsTitle: 'From active terminal to durable project context.',
    pillarsLead: 'The dashboard and project-management workflows now share the same authentication, runtime health, storage, and recovery boundaries.',
    pillars: [
      {
        index: '01', name: 'Session Operations',
        description: 'Search Codex JSONL by message, project, model, date, tags, or pin. Open a replay without returning to the original terminal.',
        features: ['Session Catalog', 'Full-message search', 'Replay · pin · tag · saved filters'],
        href: '/codexmux/docs/session-operations/', link: 'Explore session operations',
      },
      {
        index: '02', name: 'Live Session Control',
        description: 'Run parallel terminals, inspect status and timeline events, reconnect, and resume Codex work from the browser.',
        features: ['Workspace · tabs · panes', 'Status · timeline · approvals', 'Reconnect-safe terminal input'],
        href: '/codexmux/docs/live-session-view/', link: 'Operate live sessions',
      },
      {
        index: '03', name: 'Project Governance',
        description: 'Register projects under approved roots, navigate guidance and lifecycle artifacts, and review audit findings in one read model.',
        features: ['Managed Projects', 'Knowledge Index · lifecycle · audit', 'Preview · confirm · journal · rollback'],
        href: '/codexmux/docs/project-governance/', link: 'Review governance controls',
      },
      {
        index: '04', name: 'Runtime Operations',
        description: 'Keep worker health, index rebuilds, durable state backups, service restarts, and recovery on the Linux engine.',
        features: ['Worker isolation', 'Health · rebuild · backup', 'systemd user service'],
        href: '/codexmux/docs/linux-service/', link: 'Run the Linux service',
      },
    ],
    workflowEyebrow: 'Operational flow',
    workflowTitle: 'Work stays connected after the prompt finishes.',
    workflow: [
      { step: '01', title: 'Run', text: 'Create a workspace, launch Codex, and follow live status from terminal and timeline.' },
      { step: '02', title: 'Find', text: 'Use the Session Catalog to recover a prior decision, message, model, or project.' },
      { step: '03', title: 'Review', text: 'Replay the session and keep operational annotations without mutating Codex source logs.' },
      { step: '04', title: 'Govern', text: 'Inspect project guidance and lifecycle state, then preview guarded changes when authorized.' },
    ],
    boundaryEyebrow: 'Capability boundary',
    boundaryTitle: 'Clear about what works today.',
    boundaryLead: 'Support means the feature is implemented and verified. It does not imply that a fresh host already contains indexed sessions or registered projects.',
    capabilityGroups: [
      {
        state: 'Available now', tone: 'ready', description: 'Read and operate without enabling project writes.',
        items: ['Catalog search, filters, replay and annotations', 'Live terminal, status, timeline and reconnect', 'Project registration, Knowledge Index, lifecycle and audit', 'Runtime health, rebuild and durable-state backup'],
      },
      {
        state: 'Guarded actions', tone: 'guarded', description: 'Requires an approved root, write gate and explicit confirmation.',
        items: ['Versioned project scaffold', 'Artifact-by-artifact unmarked adoption', 'Fingerprint revalidation and no-replace writes', 'Private journal, recovery and latest-first rollback'],
      },
      {
        state: 'Not in current scope', tone: 'planned', description: 'Intentionally excluded; the site does not claim parity.',
        items: ['Remote collectors or multi-engine federation', 'Session deletion or retention automation', 'Arbitrary project sync, move or delete', 'Semantic merge, GSD orchestration or full-output search'],
      },
    ],
    architectureEyebrow: 'Architecture',
    architectureTitle: 'One authority, isolated workers.',
    architectureLead: 'The browser never becomes the session source or project writer. A single Linux engine owns runtime processes, indexes, backups, and approved project access.',
    architecture: [
      { label: 'Clients', title: 'Browser · optional Electron shell', detail: 'Dense operations UI over authenticated HTTP and WebSocket' },
      { label: 'Control', title: 'Custom Node server', detail: 'Pages Router, auth, API routing and runtime supervisor' },
      { label: 'Workers', title: 'Terminal · Timeline · Storage · Governance', detail: 'Typed ownership, degraded modes and independent recovery' },
      { label: 'Engine data', title: 'tmux · Codex JSONL · app DB · approved projects', detail: 'Local filesystem authority on the Linux single-engine host' },
    ],
    installEyebrow: 'Install',
    installTitle: 'Start locally. Harden before exposing it.',
    installLead: 'Node.js 20.9+, tmux 3.0+, and an authenticated Codex CLI are required on the Linux engine.',
    openBrowser: 'Open http://127.0.0.1:8122 and complete setup.',
    installGuide: 'Installation guide', serviceGuide: 'Service operations',
    docsEyebrow: 'Documentation', docsTitle: 'Choose the surface you are operating.',
    docsCards: [
      { title: 'Start a first session', text: 'Install, initialize, and open a browser workspace.', href: '/codexmux/docs/quickstart/', link: 'Quickstart' },
      { title: 'Search and replay work', text: 'Understand indexing, filters, annotations, empty states, and rebuilds.', href: '/codexmux/docs/session-operations/', link: 'Session Operations' },
      { title: 'Manage project context', text: 'Approve roots, register projects, inspect knowledge, and control writes.', href: '/codexmux/docs/project-governance/', link: 'Project Governance' },
    ],
    closingTitle: 'Keep the terminal, the session record, and the project context in one place.',
    closingText: 'Self-hosted on your Linux engine. Open source under the MIT License.',
    closingAction: 'Read the docs',
  },
  ko: {
    ...shared,
    langLabel: 'KO',
    nav: {
      capabilities: '기능', workflow: '흐름', boundary: '구현 상태', architecture: '아키텍처',
      install: '설치', docs: '문서', start: '시작하기',
    },
    hero: {
      eyebrow: 'Codex 세션 운영 · 하나의 Linux 엔진',
      title: ['작업을 실행하고,', '맥락을 다시 찾고,', '프로젝트를 관리합니다.'],
      description: 'codexmux는 실시간 Codex 제어, 지속되는 세션 검토, 안전한 프로젝트 운영을 하나의 브라우저 작업 공간에 연결합니다.',
      guide: '빠른 시작 열기', proof: ['브라우저 중심', '로컬 우선 데이터', '한국어 + 영어 UI'],
      integration: '세션 분석과 프로젝트 관리 기능은 별도 서비스가 아니라 codexmux runtime 안에 통합되어 있습니다.',
    },
    preview: {
      engine: 'Linux 엔진', ready: 'Worker 정상', sessions: '세션 탐색기',
      search: '메시지, 프로젝트, 모델, 태그 검색…',
      results: [
        { project: 'codexmux', title: 'Governed scaffold 배포', meta: 'gpt-5.6 · 항목 24개', state: '고정' },
        { project: 'runtime-v2', title: 'Worker 복구 검증', meta: 'gpt-5.6 · 항목 17개', state: '복기' },
      ],
      governance: 'Project Governance', project: 'Managed Project · codexmux',
      documents: [
        { name: 'AGENTS.md', state: 'Guidance' }, { name: 'CONTEXT.md', state: 'Indexed' },
        { name: 'Project Lifecycle', state: 'Operate' },
      ],
      action: '쓰기 전에 미리보기 필요', writeState: '보호됨',
    },
    pillarsEyebrow: '하나의 운영 화면', pillarsTitle: '실행 중 terminal부터 지속되는 project context까지.',
    pillarsLead: 'dashboard와 project-mgmt에서 검증한 흐름이 이제 동일한 인증, runtime health, storage, recovery 경계 안에서 작동합니다.',
    pillars: [
      {
        index: '01', name: '세션 운영',
        description: 'Codex JSONL을 메시지, 프로젝트, 모델, 날짜, 태그와 고정 상태로 검색하고 원래 terminal로 돌아가지 않아도 세션을 복기합니다.',
        features: ['Session Catalog', '메시지 전문 검색', '복기 · 고정 · 태그 · 저장 필터'],
        href: '/codexmux/ko/docs/session-operations/', link: '세션 운영 알아보기',
      },
      {
        index: '02', name: '실시간 세션 제어',
        description: '병렬 terminal을 실행하고 status와 timeline을 확인하며 브라우저에서 Codex 작업을 재연결하고 재개합니다.',
        features: ['Workspace · tab · pane', 'Status · timeline · approval', '재연결 안전 terminal 입력'],
        href: '/codexmux/ko/docs/live-session-view/', link: '실시간 세션 운영하기',
      },
      {
        index: '03', name: 'Project Governance',
        description: '승인 root 아래 project를 등록하고 guidance, lifecycle artifact, audit 결과를 하나의 read model에서 탐색합니다.',
        features: ['Managed Project', 'Knowledge Index · lifecycle · audit', '미리보기 · 확인 · journal · rollback'],
        href: '/codexmux/ko/docs/project-governance/', link: 'Governance 제어 확인하기',
      },
      {
        index: '04', name: 'Runtime Operations',
        description: 'Worker health, index rebuild, durable state backup, service restart와 recovery를 Linux 엔진에서 관리합니다.',
        features: ['Worker 격리', 'Health · rebuild · backup', 'systemd user service'],
        href: '/codexmux/ko/docs/linux-service/', link: 'Linux 서비스 운영하기',
      },
    ],
    workflowEyebrow: '운영 흐름', workflowTitle: 'Prompt가 끝난 뒤에도 작업 맥락은 이어집니다.',
    workflow: [
      { step: '01', title: '실행', text: 'Workspace에서 Codex를 시작하고 terminal과 timeline으로 실시간 상태를 확인합니다.' },
      { step: '02', title: '검색', text: 'Session Catalog에서 이전 결정, 메시지, 모델 또는 프로젝트를 다시 찾습니다.' },
      { step: '03', title: '검토', text: 'Codex 원본 로그를 변경하지 않고 세션을 복기하고 운영 annotation을 유지합니다.' },
      { step: '04', title: '관리', text: 'Project guidance와 lifecycle 상태를 확인하고 승인된 경우에만 변경을 미리 봅니다.' },
    ],
    boundaryEyebrow: '기능 경계', boundaryTitle: '지금 작동하는 범위를 명확하게.',
    boundaryLead: '지원 기능은 구현과 검증이 완료됐다는 뜻입니다. 새 호스트에 세션이나 Managed Project가 이미 등록되어 있다는 뜻은 아닙니다.',
    capabilityGroups: [
      {
        state: '현재 사용 가능', tone: 'ready', description: 'Project write를 켜지 않아도 읽고 운영할 수 있습니다.',
        items: ['Catalog 검색, 필터, 복기와 annotation', '실시간 terminal, status, timeline과 재연결', 'Project 등록, Knowledge Index, lifecycle과 audit', 'Runtime health, rebuild와 durable state backup'],
      },
      {
        state: '보호된 작업', tone: 'guarded', description: '승인 root, write gate와 명시적 확인이 필요합니다.',
        items: ['버전이 지정된 project scaffold', 'Artifact별 unmarked adoption', 'Fingerprint 재검증과 no-replace write', 'Private journal, recovery와 최신순 rollback'],
      },
      {
        state: '현재 범위 아님', tone: 'planned', description: '의도적으로 제외됐으며 Pages에서 parity를 주장하지 않습니다.',
        items: ['Remote collector 또는 multi-engine federation', 'Session 삭제 또는 retention 자동화', '임의 project sync, move 또는 delete', 'Semantic merge, GSD orchestration 또는 full-output search'],
      },
    ],
    architectureEyebrow: '아키텍처', architectureTitle: '하나의 authority, 격리된 worker.',
    architectureLead: '브라우저는 session source나 project writer가 되지 않습니다. 하나의 Linux 엔진이 runtime process, index, backup과 승인된 project 접근을 소유합니다.',
    architecture: [
      { label: 'Client', title: '브라우저 · 선택 Electron shell', detail: '인증된 HTTP와 WebSocket을 사용하는 고밀도 운영 UI' },
      { label: 'Control', title: 'Custom Node server', detail: 'Pages Router, 인증, API routing과 runtime supervisor' },
      { label: 'Worker', title: 'Terminal · Timeline · Storage · Governance', detail: 'Typed ownership, degraded mode와 독립 recovery' },
      { label: 'Engine data', title: 'tmux · Codex JSONL · app DB · 승인 project', detail: 'Linux 단일 엔진 호스트의 local filesystem authority' },
    ],
    installEyebrow: '설치', installTitle: '로컬에서 시작하고, 외부 공개 전에 보호하세요.',
    installLead: 'Linux 엔진에 Node.js 20.9+, tmux 3.0+와 로그인된 Codex CLI가 필요합니다.',
    openBrowser: 'http://127.0.0.1:8122를 열고 초기 설정을 완료합니다.',
    installGuide: '설치 가이드', serviceGuide: '서비스 운영',
    docsEyebrow: '문서', docsTitle: '지금 운영할 surface를 선택하세요.',
    docsCards: [
      { title: '첫 세션 시작', text: '설치하고 초기화한 뒤 브라우저 workspace를 엽니다.', href: '/codexmux/ko/docs/quickstart/', link: '빠른 시작' },
      { title: '작업 검색과 복기', text: 'Index, filter, annotation, empty state와 rebuild를 이해합니다.', href: '/codexmux/ko/docs/session-operations/', link: '세션 운영' },
      { title: 'Project context 관리', text: 'Root를 승인하고 project, knowledge와 write 경계를 관리합니다.', href: '/codexmux/ko/docs/project-governance/', link: 'Project Governance' },
    ],
    closingTitle: 'Terminal, session 기록과 project context를 한곳에 유지하세요.',
    closingText: '내 Linux 엔진에 self-hosting. MIT License 오픈소스.', closingAction: '문서 읽기',
  },
};
