const shared = {
  installCommand: 'npx --yes codexmux@latest',
  publicVersion: '0.4.23',
  sourceVersion: '0.4.24',
};

module.exports = {
  en: {
    ...shared,
    hero: {
      eyebrow: 'Codex session operations · one Linux engine',
      title: 'One Linux engine. Every Codex session.',
      description: 'Run live work, recover durable session context, and govern project guidance from one self-hosted operating surface.',
      primaryAction: 'Get started',
      secondaryAction: 'View on GitHub',
      artworkAlt: '',
      chips: ['Workspace', 'Sessions', 'Governance', 'Runtime v2'],
      note: 'Browser control · local data · guarded project writes',
    },
    quickstart: {
      eyebrow: 'Quickstart',
      title: ['Install.', 'Start.', 'Keep the context.'],
      description: 'Node.js, tmux and an authenticated Codex CLI are the only engine prerequisites.',
      guide: 'Full quickstart',
      versionNote: 'Public npm latest',
      lines: [
        { command: 'npx --yes codexmux@latest', note: 'install and launch' },
        { command: 'xdg-open http://127.0.0.1:8122', note: 'or open it manually' },
      ],
    },
    proof: {
      eyebrow: 'One operating surface',
      title: 'Move from live work to durable context without losing your place.',
      description: 'Workspace, Sessions and Governance remain distinct areas while sharing one authenticated Linux runtime.',
      caption: 'Route, entity selection and runtime status stay visually separate.',
    },
    preview: {
      engine: 'Linux engine',
      ready: '4 workers ready',
      areas: ['Workspace', 'Sessions', 'Governance'],
      search: 'Search messages, projects, models or tags',
      filter: 'Pinned · gpt-5.6 · codexmux',
      results: [
        { project: 'codexmux', title: 'Navigation selection clarity', meta: '24 entries · pinned', state: 'Selected' },
        { project: 'runtime-v2', title: 'Worker recovery verification', meta: '17 entries · replay', state: 'Ready' },
      ],
      replay: 'Session replay',
      replayTitle: 'Navigation selection clarity',
      timeline: ['User request', 'Implementation', 'Verification', 'Operate'],
      checks: 'checks passed',
      context: 'Project context',
      project: 'Managed Project · codexmux',
      documents: ['AGENTS.md · Guidance', 'CONTEXT.md · Indexed', 'Lifecycle · Operate'],
      guarded: 'Preview required before write',
    },
    capabilities: {
      eyebrow: 'The whole operating surface',
      title: 'Built for the work before, during and after the prompt.',
      description: 'Each card maps to an implemented product surface or an explicit safety boundary.',
      cards: [
        { key: 'sessions', size: 'wide', label: 'Session Operations', title: 'Search the work you already did.', text: 'Index Codex JSONL, search full messages, replay sessions, and keep pins, tags and saved filters without mutating source logs.', href: '/codexmux/docs/session-operations/', link: 'Explore Sessions' },
        { key: 'governance', size: 'tall', label: 'Project Governance', title: 'Keep project context reviewable.', text: 'Register approved roots, inspect guidance, lifecycle and audit, then preview governed changes before confirmation.', href: '/codexmux/docs/project-governance/', link: 'Review Governance' },
        { key: 'workspace', size: '', label: 'Workspace', title: 'Operate parallel sessions.', text: 'Tabs, panes, status and activity stay together while Sessions remains a separate durable catalog.' },
        { key: 'reconnect', size: '', label: 'Live control', title: 'Reconnect without losing input.', text: 'Terminal and WebSocket recovery favor session continuity on desktop and mobile.' },
        { key: 'runtime', size: 'wide', label: 'Runtime Operations', title: 'One authority. Isolated workers.', text: 'Terminal, Timeline, Storage and Governance workers fail and recover independently under one supervisor.', href: '/codexmux/docs/linux-service/', link: 'Operate the service' },
        { key: 'guarded', size: '', label: 'Guarded actions', title: 'Preview. Confirm. Recover.', text: 'Approved roots, fingerprints, private journals and rollback protect project writes.' },
        { key: 'local', size: '', label: 'Local-first', title: 'Your engine owns the data.', text: 'tmux, Codex JSONL, app databases and approved projects remain on the Linux host.' },
        { key: 'locale', size: 'wide', label: 'Accessible by default', title: 'Korean and English product UI.', text: 'Keyboard focus, reduced motion, responsive controls and explicit state labels are part of the interface contract.' },
      ],
    },
    docs: {
      eyebrow: 'Documentation map',
      title: 'Go directly to the surface you are operating.',
      action: 'Explore all docs',
      groups: [
        { title: 'Getting Started', links: [{ label: 'Installation', href: '/codexmux/docs/installation/' }, { label: 'Quickstart', href: '/codexmux/docs/quickstart/' }, { label: 'First session', href: '/codexmux/docs/first-session/' }] },
        { title: 'Session Operations', links: [{ label: 'Session Explorer', href: '/codexmux/docs/session-operations/' }, { label: 'Live session view', href: '/codexmux/docs/live-session-view/' }, { label: 'Status & notifications', href: '/codexmux/docs/session-status/' }] },
        { title: 'Project Governance', links: [{ label: 'Governance overview', href: '/codexmux/docs/project-governance/' }, { label: 'Security & auth', href: '/codexmux/docs/security-auth/' }, { label: 'Data directory', href: '/codexmux/docs/data-directory/' }] },
        { title: 'Runtime & Reference', links: [{ label: 'Linux service', href: '/codexmux/docs/linux-service/' }, { label: 'Architecture', href: '/codexmux/docs/architecture/' }, { label: 'CLI reference', href: '/codexmux/docs/cli-reference/' }] },
      ],
    },
  },
  ko: {
    ...shared,
    hero: {
      eyebrow: 'Codex 세션 운영 · 하나의 Linux 엔진',
      title: '하나의 Linux 엔진. 모든 Codex 세션.',
      description: '실시간 작업을 실행하고, 지속되는 세션 맥락을 다시 찾고, 프로젝트 guidance를 하나의 self-hosted 운영 화면에서 관리합니다.',
      primaryAction: '시작하기',
      secondaryAction: 'GitHub에서 보기',
      artworkAlt: '',
      chips: ['Workspace', 'Sessions', 'Governance', 'Runtime v2'],
      note: '브라우저 제어 · 로컬 데이터 · 보호된 project write',
    },
    quickstart: {
      eyebrow: '빠른 시작',
      title: ['설치하고.', '시작하고.', '맥락을 유지하세요.'],
      description: 'Linux 엔진에는 Node.js, tmux와 인증된 Codex CLI만 있으면 됩니다.',
      guide: '전체 빠른 시작',
      versionNote: 'Public npm latest',
      lines: [
        { command: 'npx --yes codexmux@latest', note: '설치와 실행' },
        { command: 'xdg-open http://127.0.0.1:8122', note: '또는 브라우저에서 직접 열기' },
      ],
    },
    proof: {
      eyebrow: '하나의 운영 화면',
      title: '실시간 작업에서 지속되는 맥락까지, 위치를 잃지 않고 이동합니다.',
      description: 'Workspace, Sessions, Governance는 서로 다른 영역이지만 하나의 인증된 Linux runtime을 공유합니다.',
      caption: 'Route, entity selection과 runtime status를 서로 다른 상태로 표시합니다.',
    },
    preview: {
      engine: 'Linux 엔진', ready: 'Worker 4개 정상', areas: ['Workspace', 'Sessions', 'Governance'],
      search: '메시지, 프로젝트, 모델 또는 태그 검색', filter: '고정 · gpt-5.6 · codexmux',
      results: [
        { project: 'codexmux', title: 'Navigation selection clarity', meta: '항목 24개 · 고정', state: '선택됨' },
        { project: 'runtime-v2', title: 'Worker recovery verification', meta: '항목 17개 · 복기', state: '준비' },
      ],
      replay: '세션 복기', replayTitle: 'Navigation selection clarity', timeline: ['사용자 요청', '구현', '검증', 'Operate'],
      checks: '검증 통과',
      context: 'Project context', project: 'Managed Project · codexmux',
      documents: ['AGENTS.md · Guidance', 'CONTEXT.md · Indexed', 'Lifecycle · Operate'],
      guarded: '쓰기 전에 미리보기 필요',
    },
    capabilities: {
      eyebrow: '전체 운영 surface', title: 'Prompt 전과 도중, 끝난 뒤의 작업까지.',
      description: '각 card는 구현된 제품 surface 또는 명시적인 안전 경계를 가리킵니다.',
      cards: [
        { key: 'sessions', size: 'wide', label: '세션 운영', title: '이미 수행한 작업을 다시 찾습니다.', text: 'Codex JSONL을 index하고 전문을 검색하며 원본을 변경하지 않고 세션을 복기하고 고정·태그·저장 필터를 유지합니다.', href: '/codexmux/ko/docs/session-operations/', link: 'Sessions 살펴보기' },
        { key: 'governance', size: 'tall', label: 'Project Governance', title: 'Project context를 검토 가능한 상태로.', text: '승인 root를 등록하고 guidance, lifecycle과 audit을 확인한 뒤 governed change를 확인 전에 미리 봅니다.', href: '/codexmux/ko/docs/project-governance/', link: 'Governance 확인하기' },
        { key: 'workspace', size: '', label: 'Workspace', title: '병렬 세션을 운영합니다.', text: 'Tab, pane, status와 activity를 함께 유지하며 Sessions는 별도의 durable catalog로 구분합니다.' },
        { key: 'reconnect', size: '', label: '실시간 제어', title: '입력을 잃지 않고 재연결.', text: 'Terminal과 WebSocket 복구는 desktop과 mobile에서 session 연속성을 우선합니다.' },
        { key: 'runtime', size: 'wide', label: 'Runtime Operations', title: '하나의 authority. 격리된 worker.', text: 'Terminal, Timeline, Storage와 Governance worker가 하나의 supervisor 아래에서 독립적으로 실패하고 복구합니다.', href: '/codexmux/ko/docs/linux-service/', link: '서비스 운영하기' },
        { key: 'guarded', size: '', label: '보호된 작업', title: '미리보기. 확인. 복구.', text: '승인 root, fingerprint, private journal과 rollback이 project write를 보호합니다.' },
        { key: 'local', size: '', label: '로컬 우선', title: '데이터는 내 엔진에.', text: 'tmux, Codex JSONL, app database와 승인 project가 Linux host에 남습니다.' },
        { key: 'locale', size: 'wide', label: '접근성 기본 제공', title: '한국어와 영어 제품 UI.', text: 'Keyboard focus, reduced motion, responsive control과 명시적 상태 label을 UI 계약으로 유지합니다.' },
      ],
    },
    docs: {
      eyebrow: '문서 맵', title: '지금 운영하는 surface로 바로 이동하세요.', action: '전체 문서 보기',
      groups: [
        { title: '시작하기', links: [{ label: '설치', href: '/codexmux/ko/docs/installation/' }, { label: '빠른 시작', href: '/codexmux/ko/docs/quickstart/' }, { label: '첫 세션', href: '/codexmux/ko/docs/first-session/' }] },
        { title: '세션 운영', links: [{ label: 'Session Explorer', href: '/codexmux/ko/docs/session-operations/' }, { label: '실시간 세션 뷰', href: '/codexmux/ko/docs/live-session-view/' }, { label: '상태와 알림', href: '/codexmux/ko/docs/session-status/' }] },
        { title: 'Project Governance', links: [{ label: 'Governance 개요', href: '/codexmux/ko/docs/project-governance/' }, { label: '보안과 인증', href: '/codexmux/ko/docs/security-auth/' }, { label: '데이터 디렉터리', href: '/codexmux/ko/docs/data-directory/' }] },
        { title: 'Runtime & Reference', links: [{ label: 'Linux 서비스', href: '/codexmux/ko/docs/linux-service/' }, { label: '아키텍처', href: '/codexmux/ko/docs/architecture/' }, { label: 'CLI 레퍼런스', href: '/codexmux/ko/docs/cli-reference/' }] },
      ],
    },
  },
};
